#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get update

# # For doing builds:
apt-get install -y ruby
apt-get install -y rubygems
apt-get install -y rake
apt-get install -y git-core
apt-get install -y ruby-dev
apt-get install -y libldap-ruby
apt-get install -y librrd-ruby
apt-get install -y librrd2-dev
apt-get install -y rrdtool
apt-get install -y mysql-server
apt-get install -y libmysql-ruby
apt-get install -y sqlite3
apt-get install -y libsqlite3-ruby
apt-get install -y libtest-unit-ruby
apt-get install -y mongrel libdaemons-ruby1.8

# Install Gems

wget http://rubyforge.org/frs/download.php/60718/rubygems-1.3.5.tgz
tar -zxf rubygems-1.3.5.tgz
cd rubygems-1.3.5
ruby setup.rb
gem -v
cd /tmp

gem install --no-ri --no-rdoc rspec --version 1.2.2
gem install --no-ri --no-rdoc ci_reporter mocha hoe rails cucumber rake
gem install --no-ri --no-rdoc relevance-rcov --source http://gems.github.com
gem install --no-ri --no-rdoc json stomp
gem install --no-ri --no-rdoc facter

# Configure Hudson

useradd hudson
usermod -a -G mail hudson
useradd puppet
usermod -a -G mail puppet

mkdir /home/hudson
mkdir /home/hudson/.puppet
cd /home/hudson

git config --global user.email "hudson@reductivelabs.com"
git config --global user.name "Hudson User"

echo "Slave Build completed"

