#!/bin/bash

apt-get update

export DEBIAN_FRONTEND=noninteractive
dpkg-reconfigure --frontend=noninteractive --priority=critical debconf

echo "libc6 glibc/restart-services string rsync cron" | /usr/bin/debconf-set-selections
echo "libc6 glibc/upgrade select true" | /usr/bin/debconf-set-selections

# # For doing builds:
apt-get install -y --force-yes ruby
apt-get install -y --force-yes rubygems
apt-get install -y --force-yes rake
apt-get install -y --force-yes git-core
apt-get install -y --force-yes ruby-dev
apt-get install -y --force-yes libldap-ruby
apt-get install -y --force-yes librrd-ruby
apt-get install -y --force-yes librrd2-dev
apt-get install -y --force-yes rrdtool
apt-get install -y --force-yes mysql-server
apt-get install -y --force-yes libmysql-ruby
apt-get install -y --force-yes sqlite3
apt-get install -y --force-yes libsqlite3-ruby
apt-get install -y --force-yes libtest-unit-ruby
apt-get install -y --force-yes mongrel libdaemons-ruby1.8

wget http://rubyforge.org/frs/download.php/60718/rubygems-1.3.5.tgz
tar -zxf rubygems-1.3.5.tgz
cd rubygems-1.3.5
ruby setup.rb
gem -v
cd /tmp

gem install --no-ri --no-rdoc rspec --version 1.2.2
gem install --no-ri --no-rdoc ci_reporter mocha hoe rails cucumber rake
gem install --no-ri --no-rdoc relevance-rcov --source http://gems.github.com
gem install --no-ri --no-rdoc json stomp
gem install --no-ri --no-rdoc facter

# Configure Hudson

useradd hudson
usermod -a -G mail hudson
useradd puppet
usermod -a -G mail puppet

mkdir /home/hudson
mkdir /home/hudson/.puppet
cd /home/hudson

git config --global user.email "hudson@reductivelabs.com"
git config --global user.name "Hudson User"

echo "Slave Build completed"

