#!/bin/bash

# yum update

# java apps (sun SDK)
yum install -y java-1.6.0-openjdk
yum install -y ruby rubygems ruby-shadow ruby-ldap
yum install -y rrdtool ruby-RRDtool
#rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-3.noarch.rpm
#yum install -y git
java -version 


