#!/bin/bash

# java apps (sun SDK)
rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-3.noarch.rpm
yum install -y gcc make automake
yum install -y ruby ruby-devel rubygems ruby-shadow ruby-ldap rubygem-mongrel
yum install -y rrdtool ruby-RRDtool
yum upgrade -y curl
yum install -y git
yum install -y postgresql postgresql-server postgresql-devel
yum install -y sqlite sqlite-devel
yum install -y mysql mysql-devel mysql-server

# install Gems

gem install --no-ri --no-rdoc rspec --version 1.2.2

