#!/bin/bash

# java apps (sun SDK)
emerge virtual/jdk
java -version 

# # For doing builds:
emerge dev-lang/ruby
emerge dev-ruby/rubygems
emerge dev-util/git 
emerge dev-ruby/ruby-ldap
emerge net-analyzer/rrdtool dev-ruby/ruby-rrd



